"""Delivered files carry the documented schema, not whatever survived the run.

``write_csv`` writes every column on the frame, so vendor passthrough and any
working column a step forgot to drop reached the deliverable. BATS-2023
``persons`` shipped 220 columns against 31 declared ones. ``write_only_canonical``
narrows the output to what the pipeline actually stands behind.
"""

from pathlib import Path

import polars as pl
import pytest

from data_canon.core.dataclass import CanonicalData
from processing.read_write.read_write import write_data


@pytest.fixture
def canon() -> CanonicalData:
    """One household table carrying a declared field, a vendor column and a zone id."""
    data = CanonicalData()
    data.households = pl.DataFrame(
        {
            "hh_id": [1, 2],
            "home_lat": [37.7, 37.8],
            "home_lon": [-122.4, -122.5],
            # Vendor passthrough: real BATS columns nobody here documents.
            "bicycle_type_1": [1, 0],
            "num_complete_tue_a": [3, 4],
            # Config-named, generated by add_zone_ids.
            "home_taz": [101, 202],
        }
    )
    return data


def _written(path: Path) -> list[str]:
    return pl.read_csv(path).columns


def test_requires_an_explicit_choice(canon: CanonicalData, tmp_path: Path) -> None:
    """Neither answer is safe to assume, so silence is an error.

    Defaulting to true would drop columns a project expected to deliver;
    defaulting to false would keep shipping hundreds nobody documented.
    """
    with pytest.raises(ValueError, match="write_only_canonical"):
        write_data(
            output_paths={"households": str(tmp_path / "hh.csv")},
            canonical_data=canon,
            validate_input=False,
        )


def test_canonical_only_drops_undeclared_columns(canon: CanonicalData, tmp_path: Path) -> None:
    """Declared fields stay; vendor passthrough goes."""
    out = tmp_path / "hh.csv"
    write_data(
        output_paths={"households": str(out)},
        canonical_data=canon,
        validate_input=False,
        write_only_canonical=True,
    )

    written = _written(out)
    assert "hh_id" in written
    assert "home_lat" in written
    assert "bicycle_type_1" not in written
    assert "num_complete_tue_a" not in written


def test_registered_generated_columns_survive(canon: CanonicalData, tmp_path: Path) -> None:
    """A zone id is ours even though no model can name it.

    ``home_taz`` is ``{prefix}_{zone_name}`` with the name coming from config,
    so it can never be a model field -- but dropping it would gut the output.
    """
    canon.register_generated_columns("households", ["home_taz"])
    out = tmp_path / "hh.csv"
    write_data(
        output_paths={"households": str(out)},
        canonical_data=canon,
        validate_input=False,
        write_only_canonical=True,
    )

    assert "home_taz" in _written(out)


def test_unregistered_generated_column_is_dropped(canon: CanonicalData, tmp_path: Path) -> None:
    """Registration is what makes it public -- the name alone proves nothing.

    Pattern-matching ``*_taz`` would also swallow a genuine mistake, so the step
    that created the column has to say so.
    """
    out = tmp_path / "hh.csv"
    write_data(
        output_paths={"households": str(out)},
        canonical_data=canon,
        validate_input=False,
        write_only_canonical=True,
    )

    assert "home_taz" not in _written(out)


def test_dump_everything_when_asked(canon: CanonicalData, tmp_path: Path) -> None:
    """False is a real option: debugging needs the working columns."""
    out = tmp_path / "hh.csv"
    write_data(
        output_paths={"households": str(out)},
        canonical_data=canon,
        validate_input=False,
        write_only_canonical=False,
    )

    assert _written(out) == canon.households.columns


def test_column_order_is_preserved(canon: CanonicalData, tmp_path: Path) -> None:
    """Narrowing must not reshuffle: diffs against a prior delivery stay readable."""
    canon.register_generated_columns("households", ["home_taz"])
    out = tmp_path / "hh.csv"
    write_data(
        output_paths={"households": str(out)},
        canonical_data=canon,
        validate_input=False,
        write_only_canonical=True,
    )

    written = _written(out)
    assert written == [c for c in canon.households.columns if c in written]
